apiVersion: v1
kind: ConfigMap
metadata:
  name: loja-veloz-config
  namespace: loja-veloz
  labels:
    app.kubernetes.io/part-of: loja-veloz
data:
  # URLs internas dos serviços (Service DNS do K8s)
  PEDIDOS_SERVICE_URL:          "http://pedidos-svc:8080"
  PAGAMENTOS_SERVICE_URL:       "http://pagamentos-svc:8081"
  ESTOQUE_SERVICE_URL:          "http://estoque-svc:8082"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-collector:4317"
  POSTGRES_DB:                  "loja_veloz"
  APP_VERSION:                  "1.0.0"
  RABBITMQ_URL:                 "amqp://rabbitmq-svc:5672/"
