apiVersion: v1
kind: Namespace
metadata:
  name: loja-veloz
  labels:
    app.kubernetes.io/part-of: loja-veloz
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
