apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos
  namespace: loja-veloz
  labels:
    app: pedidos
    app.kubernetes.io/part-of: loja-veloz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pedidos
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: pedidos
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port:   "8080"
        prometheus.io/path:   "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: pedidos
          image: ghcr.io/SEU_USUARIO/loja-veloz/pedidos:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: loja-veloz-config
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: loja-veloz-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: loja-veloz-secrets
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-svc:5432/loja_veloz"
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "600m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
---
apiVersion: v1
kind: Service
metadata:
  name: pedidos-svc
  namespace: loja-veloz
  labels:
    app: pedidos
spec:
  type: ClusterIP
  selector:
    app: pedidos
  ports:
    - name: http
      port: 8080
      targetPort: 8080
